NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

# Información general del emisor o del proyecto
DOCUMENTATION = [
  {
	organization_name = "Sr Arcos Labs", 
    organization_url = "https://srarcos.github.io", 
    description = "Activos oficiales emitidos por Sr Arcos Labs en la red Stellar." 
  }
]

[[CURRENCIES]]
code="XVP"
issuer="GA5DKBP7Y23UVV7IE2ZX5RCCNI7BDOQQTKSFHKCXMIR7H2UEWA4KP7DG"
display_decimals=7
# name="VipCoin"
# desc="Token para pagos en tiempo real para las plataformas Vipnet360 con suministro fijo de 21 millones y 7 decimales."
name="Xenith Vault Protocol"
desc="Token de utilidad para el ecosistema Xenith Vault en Stellar."
conditions="Suministro fijo de 21,000,000 XVP."
image="https://srarcos.github.io/.well-known/xvp_icon.png"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="AIBR"
issuer="GA5DKBP7Y23UVV7IE2ZX5RCCNI7BDOQQTKSFHKCXMIR7H2UEWA4KP7DG"
display_decimals=7
name="AI Brand Pulse"
desc="Token de análisis y reputación de marca impulsado por inteligencia artificial."
conditions="Activos emitidos por la cuenta oficial de AI Brand Pulse."
image="https://srarcos.github.io/.well-known/aibr_icon.svg"
anchor_asset_type="crypto"